/****** Object:  StoredProcedure [dbo].[ConsultaStock]    Script Date: 14/3/2020 10:31:52 ******/
DROP PROCEDURE [dbo].[ConsultaStockAsociado]
GO

-- =============================================
-- Author:		Ciro
-- Create date: 2020/03/14
-- Description:	SP para consulta de stock
-- =============================================
ALTER PROCEDURE [dbo].[ConsultaStockAsociado]
	-- Add the parameters for the stored procedure here
	@pVehiculosId INT
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    SELECT S.ARTICULOSSTOCKID, S.CODIGOBARRA, A.DESCRIPCION ARTICULO, M.DESCRIPCION MARCA, MO.DESCRIPCION MODELO, V.DESCRIPCION, V.MOTOR, VT.DESCRIPCION TIPOVEHICULO, V.ANIO, C.DESCRIPCION COLOR, TC.DESCRIPCION TIPOCOMBUSTIBLE, 
	CASE V.TIPOTRANSMISION WHEN 'M' THEN 'MANUAL' WHEN 'A' THEN 'AUTOMATICA' ELSE 'NO ESPECIFICADO' END TIPOCAJA, CA.DESCRIPCION CATEGORIA, dbo.PrecioArticulo(S.ARTICULOSID, V.CATEGORIASID, V.TIPOTRANSMISION, V.ANIO) PRECIOVENTA, V.PATENTE, 
	S.ARTICULOSID, S.VEHICULOSID, S.ESTADOSID, S.SECTORESID
	FROM ArticulosStock S INNER JOIN Vehiculos V ON S.VEHICULOSID = V.VEHICULOSID
	INNER JOIN Marcas M ON V.MARCASID = M.MARCASID
	INNER JOIN Modelos MO ON V.MODELOSID = MO.MODELOSID
	INNER JOIN Articulos A ON S.ARTICULOSID = A.ARTICULOSID
	INNER JOIN VehiculosTipo VT ON V.VEHICULOSTIPOID = VT.VEHICULOSTIPOID
	LEFT JOIN Colores C ON V.COLORESID = C.COLORESID
	LEFT JOIN TiposCombustible TC ON TC.TIPOSCOMBUSTIBLEID = V.TIPOSCOMBUSTIBLEID
	LEFT JOIN Categorias CA ON V.CATEGORIASID = CA.CATEGORIASID
	WHERE S.VEHICULOSID = @pVehiculosId
END



